export const emptyAccountDetail =  {

    "company":"",
    "account":"Account Info Not Found",
    "attention":"",
    "accountAlias":"",
    "customerName":"",
    "streetType":"",
    "streetDirection":"",
    "addressNo":"",
    "addressName":"",
    "addressLine1":"",
    "addressLine2":"",
    "addressLine3":"",
    "Telephone":"",
    "phoneExtension":0,
    "Fax":"( ) -",
    "city":"",
    "state":"",
    "postalCode":"",
    "customerCategory":"",
    "custCategoryDesc":"",
    "parcelNo":"",
    "accountClassTable":"",
    "accountClassDesc":"",
    "cashTolerance":"",
    "cashToleranceDesc":"",
    "chainCode":"",
    "chainCodeDescription":"",
    "lastUpdated":0,
    "invoiceDestination":"",
    "invoiceDestinDesc":"",
    "invoicePageBreak":"",
    "remitCode":"",
    "remitCodeDesc":"",
    "printMethod":"",
    "printMethodDesc":"",
    "invoiceSiteTotals":"",
    "invoiceSiteTaxes":"",
    "invoiceContainerTotals":"",
    "invoiceContainerTaxes":"",
    "acquisitionCode":"",
    "languageCode":"",
    "languageDesc":"",
    "SIEligible":"",
    "SIStatus":" ",
    "SIStartDate":0,
    "SIStatusDesc":" ",
    "invoiceGroupCode":"",
    "invoiceGroupDescription":"",
    "creditPolicy":" ",
    "riskCodeDesc":null,
    "originalStartDate":"",
    "lastInvoiceDate":"",
    "dunningDate":" ",
    "dunningStage":" ",
    "creditAnalyst":"",
    "userName":"",
    "chargeAdminFee":"",
    "adminFeeExc":"",
    "adminFeeExcDesc":"",
    "chargeServIntFee":"",
    "servIntFeeExc":"",
    "servIntFeeDesc":"",
    "chargeLateFee":"",
    "lateFeeExc":"",
    "lateFeeExcDesc":"",
    "lateFeePolicy":"",
    "lateFeePolicyDesc":"",
    "chargeFuelFee":"",
    "fuelFeeExc":"",
    "fuelFeeExcDesc":"",
    "nextReviewDate":0,
    "chargeEnvrFee":"",
    "EnvrFeeExc":"",
    "EnvrFeeExcDesc":"",
    "dupCopy":"",
    "EDIReq":"",
    "brokerCode":"",
    "accountGroup":" ",
    "ePortalCustomer":"",
    "quickPay":"",
    "NaFlag":null,
    sites: [
      {
"site":"Site Info Not Found",
"siteName":"",
"city":"",
"addressName":"",
"stateProvince":"",
"postalCode":"",
"streetDirection":"",
"addressNbrName":"",
"siteAddress2":"",
"streetNumber":"",
"streetType":"",
"addressSuite":"",
"lastUpdateDate":0,
"vendorNumber":" ",
"vendorSubtype":" ",
"serviceContact":"",
"contactTitle":"",
"phoneNumber":"",
"phoneExtension":0,
"contractPriceIndex":"",
"closeDate":0,
"contract#":"",
"Term":0,
"termDescription":"",
"effectiveDate":0,
"expiryDate":0,
"reviewDate":0,
"CPIIndicator":"N",
"contractStatus":" ",
"contractStatusDesc":null,
"purchaseOrder":"",
"authorizedBy":"",
"authorizedByTitle":"",
"serviceContactTitle":"",
"SICCode":" ",
"SICCodeDesc":null,
"salesRep":"",
"salesRepName":"",
"sharedContainers":"",
"territoryCode":"",
"territoryCodeDesc":"",
"taxCode":"",
"taxCodeDesc":"",
"taxExempt":"",
"lastUpdated":0,
"originalStartDate":0,
      }
    ]
  };